20221230-咪咕新增9个域名/h5liveolpicga.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf
20221230-咪咕新增9个域名/h5liveolpicga.miguvideo.com/SNS/nginx/h5liveolpicga.miguvideo.com.conf
20221230-咪咕新增9个域名/hlstrialmgsplive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn.conf
20221230-咪咕新增9个域名/hlstrialmgsplive.miguvideo.com/SNS/nginx/hlstrialmgsplive.miguvideo.com.conf
20221230-咪咕新增9个域名/yy.migu.cmvideo.cn/SNS/nginx/yy.migu.cmvideo.cn.conf
20221230-咪咕视讯需求/hlsmgsplive.a208.ottcn.com/CCS/nginx/hlsmgsplive.a208.ottcn.com-l2.conf:
20221230-咪咕视讯需求/hlsmgsplive.a208.ottcn.com/SNS/nginx/hlsmgsplive.a208.ottcn.com.conf:
20221230-咪咕视讯需求/hlsmgsplive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn.conf:
20221230-咪咕视讯需求/hlsmgsplive.miguvideo.com/SNS/nginx/hlsmgsplive.miguvideo.com.conf:
20221230-咪咕视讯需求/mgsp.live.miguvideo.com/CCS/nginx/live2.cache.cmvideo.cn-l2.conf:
20221230-咪咕视讯需求/mgsp.live.miguvideo.com/SNS/nginx/mgsp.live.miguvideo.com.conf:
20230703-咪咕直播/hlsdmzymgsplive.miguvideo.com/SNS/nginx/hlsdmzymgsplive.miguvideo.com.conf:
20230703-咪咕直播/hlszymgsplive.a208.ottcn.com/SNS/nginx/hlszymgsplive.a208.ottcn.com.conf:
20230703-咪咕直播/hlszytrialmgsplive.a208.ottcn.com/SNS/nginx/hlszytrialmgsplive.a208.ottcn.com.conf:
20230703-咪咕直播/hlszytrialmgsplive.miguvideo.com/SNS/nginx/hlszytrialmgsplive.miguvideo.com.conf:
HY600/315.live.cmvideo.cn/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/315.live.cmvideo.cn/SNS/nginx/315.live.cmvideo.cn.conf:
HY600/cdnmgsplive.migu.ppsport.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/cdnmgsplive.migu.ppsport.com/SNS/nginx/cdnmgsplive.migu.ppsport.com.conf:
HY600/cdnmgzblive.migu.ppsport.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/cdnmgzblive.migu.ppsport.com/SNS/nginx/cdnmgzblive.migu.ppsport.com.conf:
HY600/dpzx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/dpzx.live.ipplus.miguvideo.com/SNS/nginx/dpzx.live.ipplus.miguvideo.com.conf:
HY600/dyth.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/dyth.live.ipplus.miguvideo.com/SNS/nginx/dyth.live.ipplus.miguvideo.com.conf:
HY600/dzmmgsplive.miguvideo.com/SNS/nginx/dzmmgsplive.miguvideo.com.conf:
HY600/h5liveolpicga.miguvideo.com/CCS/nginx/h5liveolpicga.miguvideo.com-l2.conf:
HY600/h5liveolpicga.miguvideo.com/SNS/nginx/h5liveolpicga.miguvideo.com.conf:
HY600/hlsbkmgsplive.miguvideo.com/SNS/nginx/hlsbkmgsplive.miguvideo.com.conf:
HY600/hlsbkmgspvod.miguvideo.com/SNS/nginx/hlsbkmgspvod.miguvideo.com.conf:
HY600/hlsdofviewmgsplive.miguvideo.com/CCS/nginx/livedofview.cache.cmvideo.cn-l2.conf:
HY600/hlsdofviewmgsplive.miguvideo.com/SNS/nginx/hlsdofviewmgsplive.miguvideo.com.conf:
HY600/hlslive.aikan.miguvideo.com/SNS/nginx/hlslive.aikan.miguvideo.com.conf:
HY600/hlslive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/hlslive.miguvideo.com/SNS/nginx/hlslive.miguvideo.com.conf:
HY600/hlslive2.aikan.miguvideo.com/SNS/nginx/hlslive2.aikan.miguvideo.com.conf:
HY600/hlsmgzblive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/hlsmgzblive.miguvideo.com/SNS/nginx/hlsmgzblive.miguvideo.com.conf:
HY600/hlsmlzqmgsplive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/hlsmlzqmgsplive.miguvideo.com/SNS/nginx/hlsmlzqmgsplive.miguvideo.com.conf:
HY600/hlstrialmgsplive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/hlstrialmgsplive.miguvideo.com/SNS/nginx/hlstrialmgsplive.miguvideo.com.conf:
HY600/ipad.cmvideo.cn/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/ipad.cmvideo.cn/SNS/nginx/ipad.cmvideo.cn.conf:
HY600/jdth.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/jdth.live.ipplus.miguvideo.com/SNS/nginx/jdth.live.ipplus.miguvideo.com.conf:
HY600/jzth.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/jzth.live.ipplus.miguvideo.com/SNS/nginx/jzth.live.ipplus.miguvideo.com.conf:
HY600/live.cache.cmvideo.cn/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/live.gj.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/live.gj.miguvideo.com/SNS/nginx/live.gj.miguvideo.com.conf:
HY600/live.gq.miguvideo.com/SNS/nginx/live.gq.miguvideo.com.conf:
HY600/live.harvest.miguvideo.com/SNS/nginx/live.harvest.miguvideo.com.conf:
HY600/live.hcs.cmvideo.cn/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/live.hcs.cmvideo.cn/SNS/nginx/live.hcs.cmvideo.cn.conf:
HY600/mgtest2.live.miguvideo.com/CCS/nginx/live.cache2.cmvideo.cn-l2.conf:
HY600/mgtest2.live.miguvideo.com/SNS/nginx/mgtest2.live.miguvideo.com.conf:
HY600/mgvr.live.miguvideo.com/CCS/nginx/mgvr.live.miguvideo.com-l2.conf:
HY600/mgvr.live.miguvideo.com/SNS/nginx/mgvr.live.miguvideo.com.conf:
HY600/miguclive.miguvideo.com/CCS/nginx/miguclive.miguvideo.com-l2.conf:
HY600/miguclive.miguvideo.com/SNS/nginx/miguclive.miguvideo.com.conf:
HY600/miguyylive.lovev.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/miguyylive.lovev.com/SNS/nginx/miguyylive.lovev.com.conf:
HY600/pv1live.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/pv1live.miguvideo.com/SNS/nginx/pv1live.miguvideo.com.conf:
HY600/sszx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/sszx.live.ipplus.miguvideo.com/SNS/nginx/sszx.live.ipplus.miguvideo.com.conf:
HY600/trialmgsp.live.miguvideo.com/CCS/nginx/live2.cache.cmvideo.cn-l2.conf:
HY600/trialmgsp.live.miguvideo.com/SNS/nginx/trialmgsp.live.miguvideo.com.conf:
HY600/tyth.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/tyth.live.ipplus.miguvideo.com/SNS/nginx/tyth.live.ipplus.miguvideo.com.conf:
HY600/tyzx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/tyzx.live.ipplus.miguvideo.com/SNS/nginx/tyzx.live.ipplus.miguvideo.com.conf:
HY600/v6hlsmgsplive.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/v6hlsmgsplive.miguvideo.com/SNS/nginx/v6hlsmgsplive.miguvideo.com.conf:
HY600/yscx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/yscx.live.ipplus.miguvideo.com/SNS/nginx/yscx.live.ipplus.miguvideo.com.conf:
HY600/ysjx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/ysjx.live.ipplus.miguvideo.com/SNS/nginx/ysjx.live.ipplus.miguvideo.com.conf:
HY600/ywdofviewmgsplive.miguvideo.com/CCS/nginx/livedofview.cache.cmvideo.cn-l2.conf:
HY600/ywdofviewmgsplive.miguvideo.com/SNS/nginx/ywdofviewmgsplive.miguvideo.com.conf:
HY600/yy.migu.cmvideo.cn/SNS/nginx/yy.migu.cmvideo.cn.conf:
HY600/zycx.live.ipplus.miguvideo.com/CCS/nginx/live.cache.cmvideo.cn-l2.conf:
HY600/zycx.live.ipplus.miguvideo.com/SNS/nginx/zycx.live.ipplus.miguvideo.com.conf:
migu/hlsdofviewmgsplive.aikan.miguvideo.com/CCS/nginx/hlsdofviewmgsplive.aikan.miguvideo.com-l2.conf:
migu/hlsdofviewmgsplive.aikan.miguvideo.com/SNS/nginx/hlsdofviewmgsplive.aikan.miguvideo.com.conf:
migu/hlsliveqiangjun.miguvideo.com/SNS/nginx/hlsliveqiangjun.miguvideo.com.conf:
migu/hlstrialmgsplive.a208.ottcn.com/SNS/nginx/hlstrialmgsplive.a208.ottcn.com.conf:
migu/hlszymgsplive.miguvideo.com/SNS/nginx/hlszymgsplive.miguvideo.com_spread.conf:
migu/hlszymgsplive.miguvideo.com/SNS/nginx/hlszymgsplive.miguvideo.com.conf:
migu/lightzylive.miguvideo.com/SNS/nginx/lightzylive.miguvideo.com.conf:
