20220630-第二阶段/mgsp.vod.miguvideo.com/SNS/nginx/mgsp.vod.miguvideo.com.conf
20221109-视界云天/hwvideo.izuiyou.com.conf/CCS/nginx/hwvideo.izuiyou.com.conf
20221109-视界云天/hwvideo.izuiyou.com.conf/SNS/nginx/hwvideo.izuiyou.com.conf
20221122-腾讯域名适配/mmgamevideo.qpic.cn/CCS/nginx/mmgamevideo.qpic.cn.conf
20221122-腾讯域名适配/mmgamevideo.qpic.cn/SNS/nginx/mmgamevideo.qpic.cn.conf
20221122-腾讯域名适配/mpvideo.qpic.cn/CCS/nginx/mpvideo.qpic.cn.conf
20221122-腾讯域名适配/mpvideo.qpic.cn/SNS/nginx/mpvideo.qpic.cn.conf
20221129-BPM适配需求/cyyxwzqjifei.jingpintest.xyz/CCS/nginx/cyyxwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/cyyxwzqjifei.jingpintest.xyz/SNS/nginx/cyyxwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/cyyxwzqjifei1.jingpintest.xyz/CCS/nginx/cyyxwzqjifei1.jingpintest.xyz.conf
20221129-BPM适配需求/cyyxwzqjifei1.jingpintest.xyz/SNS/nginx/cyyxwzqjifei1.jingpintest.xyz.conf
20221129-BPM适配需求/shm01xwzqjifei.jingpintest.xyz/CCS/nginx/shm01xwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/shm01xwzqjifei.jingpintest.xyz/SNS/nginx/shm01xwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/xcl2xwzqjifei.jingpintest.xyz/CCS/nginx/xcl2xwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/xcl2xwzqjifei.jingpintest.xyz/SNS/nginx/xcl2xwzqjifei.jingpintest.xyz.conf
20221129-BPM适配需求/xcl6xwzqtest01.jingpintest.xyz/CCS/nginx/xcl6xwzqtest01.jingpintest.xyz.conf
20221129-BPM适配需求/xcl6xwzqtest01.jingpintest.xyz/SNS/nginx/xcl6xwzqtest01.jingpintest.xyz.conf
20221230-咪咕视讯需求/hlsmgspdl.miguvideo.com/SNS/nginx/hlsmgspdl.miguvideo.com.conf
20221230-咪咕视讯需求/hlsmgspvod.miguvideo.com/SNS/nginx/hlsmgspvod.miguvideo.com.conf
20221230-咪咕视讯需求/mgsp.vod.miguvideo.com/SNS/nginx/mgsp.vod.miguvideo.com.conf
20221230-咪咕视频需求配置变更/hlszymgspvod.miguvideo.com/SNS/nginx/hlszymgspvod.miguvideo.com.conf
HY600/315.dls.cmvideo.cn/SNS/nginx/315.dls.cmvideo.cn.conf:
HY600/hls.mgzbvod.miguvideo.com/SNS/nginx/hls.mgzbvod.miguvideo.com.conf
HY600/hlsmgspvod.a208.ottcn.com/SNS/nginx/hlsmgspvod.a208.ottcn.com.conf
HY600/hlsvod.aikan.miguvideo.com/SNS/nginx/hlsvod.aikan.miguvideo.com.conf
HY600/hlsvod2.aikan.miguvideo.com/SNS/nginx/hlsvod2.aikan.miguvideo.com.conf
HY600/iphone.cmvideo.cn/SNS/nginx/iphone.cmvideo.cn.conf
HY600/ivr.miguvideo.com/SNS/nginx/ivr.miguvideo.com.conf
HY600/miguyydrmvod.lovev.com/SNS/nginx/miguyydrmvod.lovev.com.conf
HY600/miguyyvod.lovev.com/SNS/nginx/miguyyvod.lovev.com.conf
HY600/yuetingbao.vod.miguvideo.com/CCS/nginx/yuetingbao.vod.miguvideo.com-l2.conf
HY600/yuetingbao.vod.miguvideo.com/SNS/nginx/yuetingbao.vod.miguvideo.com.conf
HY600/zego.vod.miguvideo.com/CCS/nginx/zego.vod.miguvideo.com-l2.conf
HY600/zego.vod.miguvideo.com/SNS/nginx/zego.vod.miguvideo.com.conf
migu/drmvod.aikan.miguvideo.com/SNS/nginx/drmvod.aikan.miguvideo.com.conf
migu/hlsdofviewmgspvod.aikan.miguvideo.com/SNS/nginx/hlsdofviewmgspvod.aikan.miguvideo.com.conf
migu/hlsvodqiangjun.miguvideo.com/SNS/nginx/hlsvodqiangjun.miguvideo.com.conf
migu/hlszymgspvod.a208.ottcn.com/hlszymgspvod.a208.ottcn.com/SNS/nginx/hlszymgspvod.a208.ottcn.com.conf
migu/hlszymgspvod.miguvideo.com/SNS/nginx/hlszymgspvod.miguvideo.com.conf
migu/lightzyvod.miguvideo.com/SNS/nginx/lightzyvod.miguvideo.com.conf
