server {
    listen *:80;
    listen 39.135.97.82:80;
    listen [2409:8087:2801:0021:0030::0012]:80;

    server_name          test.asp.com; 
    index  index.html index.htm index.php;
    set $loghost "xx";
    location / {
        root /usr/share/nginx/origin;
        #access_by_lua_file    /etc/nginx/lua/asp-debug.lua;
    }
    more_set_headers "Debug:1";
}

server {
    listen       80;
    server_name  -;

    more_set_headers "NO_SERVICE: 1";
    more_set_headers "Debug:default";
    more_clear_headers 'Server';

    return 403;
}